name: IzmirBusApp
options:
  bundleIdPrefix: com.izmir
targets:
  IzmirBusApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: [Sources]
    info:
      path: Sources/Info.plist
      properties:
        CFBundleVersion: 1
        CFBundleShortVersionString: 1.0
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
